# Source: heat/templates/secret-db.yaml
apiVersion: v1
kind: Secret
metadata:
  name: heat-db-user
type: Opaque
data:
  DB_CONNECTION: mysql+pymysql://heat:password@mariadb.openstack.svc.cluster.local:3306/heat
