# Source: heat/templates/secret-keystone.yaml
apiVersion: v1
kind: Secret
metadata:
  name: heat-keystone-user
type: Opaque
data:  
  OS_AUTH_URL: http://keystone-api.openstack.svc.cluster.local:5000/v3
  OS_REGION_NAME: RegionOne
  OS_INTERFACE: internal
  OS_PROJECT_DOMAIN_NAME: service
  OS_PROJECT_NAME: service
  OS_USER_DOMAIN_NAME: service
  OS_USERNAME: heat
  OS_PASSWORD: password
  OS_DEFAULT_DOMAIN: default
