# Source: heat/templates/secret-keystone.yaml
apiVersion: v1
kind: Secret
metadata:
  name: heat-keystone-stack-user
type: Opaque
data:
  OS_AUTH_URL: http://keystone-api.openstack.svc.cluster.local:5000/v3
  OS_REGION_NAME: RegionOne
  OS_DOMAIN_NAME: heat
  OS_USERNAME: heat-domain
  OS_PASSWORD: password