# Source: heat/templates/secret-keystone.yaml
apiVersion: v1
kind: Secret
metadata:
  name: heat-keystone-admin
type: Opaque
data:  
  OS_AUTH_URL: http://keystone-api.openstack.svc.cluster.local:5000/v3
  OS_REGION_NAME: RegionOne
  OS_INTERFACE: internal
  OS_PROJECT_DOMAIN_NAME: default
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_NAME: default
  OS_USERNAME: admin
  OS_PASSWORD: password
  OS_DEFAULT_DOMAIN: default
