# Source: heat/templates/secret-rabbitmq.yaml
apiVersion: v1
kind: Secret
metadata:
  name: heat-rabbitmq-user
type: Opaque
data:
  RABBITMQ_CONNECTION: rabbit://heat:password@rabbitmq.openstack.svc.cluster.local:15672/heat

