# Source: heat/templates/job-ks-service.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "heat-ks-service"
  labels:
    release_group: openstack-keystone
    application: heat
    component: ks-service
  annotations:
    
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-3"
spec:
  backoffLimit: 1000
  template:
    metadata:
      labels:
        release_group: openstack-keystone
        application: heat
        component: ks-service
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
    spec:
      serviceAccountName: heat-ks-service
      restartPolicy: OnFailure
            
      nodeSelector:
        openstack-control-plane: enabled

      containers:
        - name: "orchestration-ks-service-registration"
          image: docker.io/openstackhelm/heat:stein-ubuntu_bionic
          imagePullPolicy: IfNotPresent
          
          command:
            - /bin/bash
            - -c
            - /tmp/ks-service.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: ks-service-sh
              mountPath: /tmp/ks-service.sh
              subPath: ks-service.sh
              readOnly: true
            
          env:            
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_AUTH_URL
              value: "http://keystone-api.openstack.svc.cluster.local:5000/v3"
            - name: OS_REGION_NAME
              value: "RegionOne"
            - name: OS_INTERFACE
              value: "internal"
            - name: OS_ENDPOINT_TYPE
              value: "internal"
            - name: OS_PROJECT_DOMAIN_NAME
              value: "default"
            - name: OS_PROJECT_NAME
              value: "admin"
            - name: OS_USER_DOMAIN_NAME
              value: "default"
            - name: OS_USERNAME
              value: "admin"
            - name: OS_PASSWORD
              value: "password"
            - name: OS_DEFAULT_DOMAIN
              value: "default"
            - name: OS_SERVICE_NAME
              value: "heat"
            - name: OS_SERVICE_TYPE
              value: "orchestration"

        - name: "cloudformation-ks-service-registration"
          image: docker.io/openstackhelm/heat:stein-ubuntu_bionic
          imagePullPolicy: IfNotPresent
          
          command:
            - /bin/bash
            - -c
            - /tmp/ks-service.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: ks-service-sh
              mountPath: /tmp/ks-service.sh
              subPath: ks-service.sh
              readOnly: true
            
          env:            
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_AUTH_URL
          value: "http://keystone-api.openstack.svc.cluster.local:5000/v3"
        - name: OS_REGION_NAME
          value: "RegionOne"
        - name: OS_INTERFACE
          value: "internal"
        - name: OS_ENDPOINT_TYPE
          value: "internal"
        - name: OS_PROJECT_DOMAIN_NAME
          value: "default"
        - name: OS_PROJECT_NAME
          value: "admin"
        - name: OS_USER_DOMAIN_NAME
          value: "default"
        - name: OS_USERNAME
          value: "admin"
        - name: OS_PASSWORD
          value: "password"
        - name: OS_DEFAULT_DOMAIN
          value: "default"
        - name: OS_SERVICE_NAME
          value: "heat-cfn"
        - name: OS_SERVICE_TYPE
          value: "cloudformation"
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: ks-service-sh
          configMap:
            name: "heat-bin"
            defaultMode: 0555
