# Source: heat/templates/job-ks-user.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "heat-ks-user"
  labels:
    release_group: openstack-keystone
    application: heat
    component: ks-user
  annotations:
    
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-1"
spec:
  backoffLimit: 1000
  template:
    metadata:
      labels:
        release_group: openstack-keystone
        application: heat
        component: ks-user
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
    spec:
      serviceAccountName: "heat-ks-user"
      securityContext:
        runAsUser: 42424
      restartPolicy: OnFailure
            
      nodeSelector:
        openstack-control-plane: enabled
 
      containers:
        - name: ks-user
          image: docker.io/openstackhelm/heat:stein-ubuntu_bionic
          imagePullPolicy: IfNotPresent
          
          
          command:
            - /bin/bash
            - -c
            - /tmp/ks-user.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: ks-user-sh
              mountPath: /tmp/ks-user.sh
              subPath: ks-user.sh
              readOnly: true
            
          env:            
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_AUTH_URL
              value: http://keystone-api.openstack.svc.cluster.local:5000/v3
            - name: OS_REGION_NAME
              value: RegionOne
            - name: OS_INTERFACE
              value: internal
            - name: OS_ENDPOINT_TYPE
              value: internal
            - name: OS_PROJECT_DOMAIN_NAME
              value: default
            - name: OS_PROJECT_NAME
              value: admin
            - name: OS_USER_DOMAIN_NAME
              value: default
            - name: OS_USERNAME
              value: admin
            - name: OS_PASSWORD
              value: password
            - name: OS_DEFAULT_DOMAIN
              value: default
            - name: SERVICE_OS_SERVICE_NAME
              value: "heat"                       
            - name: SERVICE_OS_REGION_NAME
              value: RegionOne
            - name: SERVICE_OS_PROJECT_DOMAIN_NAME
              value: service
            - name: SERVICE_OS_PROJECT_NAME
              value: service
            - name: SERVICE_OS_USER_DOMAIN_NAME
              value: service
            - name: SERVICE_OS_USERNAME
              value: heat
            - name: SERVICE_OS_PASSWORD
              value: password
            - name: SERVICE_OS_ROLES
              value: "admin"
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: ks-user-sh
          configMap:
            name: "heat-bin"
            defaultMode: 0555
